[book]
title = "Electronic Resource Management"
authors = "C. Sean Burns"
description = "Lectures on library electronic resource management"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/cseanburns/electronic_resource_mgmt"
site-url = "https://cseanburns.net"

[output.html.print]
enable = true
page-break = true
